#!/usr/bin/env ansible-playbook
---
- name: deploy python env
  hosts: vagrant
  become_user: root
  become: yes
  roles:
    # https://github.com/dirn/ansible-pyenv
    - role: dirn.pyenv
      pyenv_runcom: ~/.bashrc
      pyenv_versions:
        - 2.7.13
        - 3.6.0
      pyenv_default_versions:
        - 3.6.0
      pyenv_project_versions:
        - 3.6.0