---

- name: download install script.
  get_url: dest=/tmp/pyenv.sh url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer

- name: install pyenv.
  shell: /bin/bash /tmp/pyenv.sh

# - name: mkdir versions.
#   shell: mkdir ~/.pyenv/versions

- name: append profile.
  shell: echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.profile && echo 'eval "$(pyenv init -)"' >> ~/.profile && echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile

- name: Install deps pkg.
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - libreadline-dev
    - libsqlite3-dev
    - libncurses5-dev
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - make
    - llvm
    - wget
    - curl

- name: pyenv install versions.
  shell: source ~/profile && pyenv install 3.6.0

# sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
# libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev